server:
  port: 9903
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'shopping-content-ms'
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'D:\\file'
pagehelper:
  helper-dialect: mysql
  reasonable: true

