server:
  port: 9904
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'shopping-page-ms'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true 
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
pagehelper:
  helper-dialect: mysql
  reasonable: true

 